# Generated by Django 4.2.1 on 2023-06-10 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creffeny', '0002_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(default='static/icons/sociable_saturn.png', upload_to='static/profile_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
